language: en-US
early_access: false
enable_free_tier: true

reviews:
  profile: chill
  auto_review:
    enabled: true
    auto_incremental: true
    drafts: false
    base_branches:
      - main

path_filters:
  - "!/*.md"
  - "!/pnpm-lock.yaml"
  - "!/*.Zone.Identifier"
  - "!/.trae/"

chat:
  auto_reply: true

# Unit test generation (beta)
unit_tests:
  enabled: true
  mode: comment
  framework: vitest
  test_files:
    - src/repositories/**/*.ts
    - src/lib/**/*.ts
    - src/components/**/*.tsx
  exclude:
    - "**/*.test.ts"
    - "**/*.test.tsx"
