# yaml-language-server: $schema= `https://coderabbit.ai/integrations/schema.v2.json` 

early_access: true
language: "en-US"

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT REVIEW"
    drafts: false
    base_branches:
      - ".*"

  path_filters:
    excluded:
      - "pnpm-lock.yaml"
      - "package-lock.json"
      - "**/*.md"
      - ".github/**"

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: "auto"
