version: "2"
reviews:
  path_filters:
    - "!dist/"
    - "!/.json"
    - "!**/.lock"
  auto_review:
    enabled: true
    drafts: false
    ignore_titles: ["WIP", "dont-merge"]
    review_status: true
