#!/usr/bin/env python3
"""
Image Path Mapper - Fuzzy match database models to physical image files
Generates SQL UPDATE statements to sync hero_image_url and hover_image_url

Usage: python3 scripts/map_image_paths.py
Output: scripts/auto_mapped.sql, scripts/manual_review.csv
"""

import json
import glob
import os
import re
from difflib import SequenceMatcher

# Configuration
FUZZY_THRESHOLD = 0.6  # Minimum similarity score (0.0-1.0)
HIGH_CONFIDENCE_THRESHOLD = 0.7  # Auto-apply threshold

def fuzzy_match(model_str, filenames, threshold=FUZZY_THRESHOLD):
    """Find best matching filename for model using fuzzy string matching"""
    model_clean = re.sub(r'[^a-z0-9]', '', model_str.lower())

    best_match = None
    best_score = 0

    for fn in filenames:
        fn_clean = re.sub(r'[^a-z0-9]', '', fn.lower().replace('.jpg', '').replace('.png', '').replace('.webp', ''))
        score = SequenceMatcher(None, model_clean, fn_clean).ratio()

        if score > best_score and score >= threshold:
            best_score = score
            best_match = fn

    return best_match, best_score

def load_models():
    """Load all models from Supabase via REST API"""
    api_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxidHRtaHdja2NyZmR5bXd5dWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI2MzYyNzAsImV4cCI6MjA3ODIxMjI3MH0.kw9jPN7GuzTlAims_7B_UEnicaVmGklBiQF9IlVE_I4"
    url = "https://lbttmhwckcrfdymwyuhn.supabase.co/rest/v1/models?select=id,name,brands(name)"

    import subprocess
    result = subprocess.run(
        ['curl', '-s', '-H', f'apikey: {api_key}', url],
        capture_output=True,
        text=True
    )

    return json.loads(result.stdout)

def main():
    print("🔍 Image Path Mapper - Starting...")
    print(f"   Fuzzy threshold: {FUZZY_THRESHOLD}")
    print(f"   High confidence threshold: {HIGH_CONFIDENCE_THRESHOLD}\n")

    # Load all models from database
    print("📊 Loading models from Supabase...")
    models = load_models()
    print(f"   Found {len(models)} models\n")

    # Get physical files
    print("📁 Scanning physical files...")
    hero_files = [os.path.basename(f) for f in glob.glob('public/images/vehicles/hero/*.jpg')]
    hover_files = [os.path.basename(f) for f in glob.glob('public/images/vehicles/hover/*.jpg')]
    print(f"   Hero images: {len(hero_files)} files")
    print(f"   Hover images: {len(hover_files)} files\n")

    # Generate mappings
    print("🤖 Running fuzzy matcher...\n")
    sql_lines = [
        "-- Auto-generated image path mappings",
        "-- Generated by: scripts/map_image_paths.py",
        "-- Fuzzy matching threshold: " + str(FUZZY_THRESHOLD),
        "",
        "BEGIN;",
        ""
    ]

    manual_review = []
    hero_matches = 0
    hover_matches = 0
    hero_low_confidence = 0
    hover_low_confidence = 0

    for m in models:
        brand = m['brands']['name'] if m['brands'] else 'Unknown'
        name = m['name']
        model_id = m['id']
        search_str = f"{brand} {name}"

        # Try hero image
        hero_match, hero_score = fuzzy_match(search_str, hero_files)

        if hero_match and hero_score >= HIGH_CONFIDENCE_THRESHOLD:
            sql_lines.append(
                f"UPDATE models SET hero_image_url = '/images/vehicles/hero/{hero_match}' "
                f"WHERE id = '{model_id}'; -- {brand} {name} (confidence: {hero_score:.2f})"
            )
            hero_matches += 1
            print(f"✓ Hero: {brand} {name} → {hero_match} ({hero_score:.2f})")
        elif hero_match and hero_score >= FUZZY_THRESHOLD:
            manual_review.append(f"{model_id},{brand},{name},hero,{hero_score:.2f},{hero_match}")
            hero_low_confidence += 1
            print(f"⚠ Hero: {brand} {name} → {hero_match} ({hero_score:.2f}) [LOW CONFIDENCE]")
        else:
            score_display = f"{hero_score:.2f}" if hero_match else "0.00"
            manual_review.append(f"{model_id},{brand},{name},hero,{score_display},NO_MATCH")
            print(f"✗ Hero: {brand} {name} → NO MATCH")

        # Try hover image
        hover_match, hover_score = fuzzy_match(search_str, hover_files)

        if hover_match and hover_score >= HIGH_CONFIDENCE_THRESHOLD:
            sql_lines.append(
                f"UPDATE models SET hover_image_url = '/images/vehicles/hover/{hover_match}' "
                f"WHERE id = '{model_id}'; -- {brand} {name} (confidence: {hover_score:.2f})"
            )
            hover_matches += 1
        elif hover_match and hover_score >= FUZZY_THRESHOLD:
            manual_review.append(f"{model_id},{brand},{name},hover,{hover_score:.2f},{hover_match}")
            hover_low_confidence += 1
        else:
            score_display = f"{hover_score:.2f}" if hover_match else "0.00"
            manual_review.append(f"{model_id},{brand},{name},hover,{score_display},NO_MATCH")

    sql_lines.append("")
    sql_lines.append("COMMIT;")
    sql_lines.append("")
    sql_lines.append(f"-- Summary:")
    sql_lines.append(f"-- Hero images: {hero_matches} high-confidence matches")
    sql_lines.append(f"-- Hover images: {hover_matches} high-confidence matches")
    sql_lines.append(f"-- Total UPDATE statements: {hero_matches + hover_matches}")
    sql_lines.append(f"-- Low confidence items: {hero_low_confidence + hover_low_confidence}")
    sql_lines.append(f"-- Items needing manual review: {len(manual_review)}")

    # Write outputs
    with open('scripts/auto_mapped.sql', 'w') as f:
        f.write('\n'.join(sql_lines))

    with open('scripts/manual_review.csv', 'w') as f:
        f.write('model_id,brand,name,type,confidence_score,matched_file\n')
        f.write('\n'.join(manual_review))

    # Print summary
    print("\n" + "="*60)
    print("📊 MAPPING SUMMARY")
    print("="*60)
    print(f"Total models processed: {len(models)}")
    print(f"\n✅ HIGH CONFIDENCE (≥{HIGH_CONFIDENCE_THRESHOLD}):")
    print(f"   Hero images:  {hero_matches} matches")
    print(f"   Hover images: {hover_matches} matches")
    print(f"   Total SQL UPDATE statements: {hero_matches + hover_matches}")
    print(f"\n⚠️  LOW CONFIDENCE ({FUZZY_THRESHOLD} - {HIGH_CONFIDENCE_THRESHOLD}):")
    print(f"   Hero:  {hero_low_confidence} items")
    print(f"   Hover: {hover_low_confidence} items")
    print(f"\n❌ NO MATCH (<{FUZZY_THRESHOLD}):")
    no_match_count = len(manual_review) - hero_low_confidence - hover_low_confidence
    print(f"   {no_match_count} items")
    print(f"\n📝 Files generated:")
    print(f"   scripts/auto_mapped.sql ({hero_matches + hover_matches} UPDATE statements)")
    print(f"   scripts/manual_review.csv ({len(manual_review)} items for human review)")
    print("\n✨ Next steps:")
    print("   1. Review scripts/manual_review.csv for low-confidence matches")
    print("   2. Manually verify ambiguous cases (MG ZS vs MG ZS EV, etc.)")
    print("   3. Append verified UPDATE statements to auto_mapped.sql")
    print("   4. Test SQL on staging/dev database before production")
    print("="*60)

if __name__ == '__main__':
    main()
