-- Generated by scripts/generate_image_updates.py
-- Run with: psql $SUPABASE_URL < scripts/update_image_urls.sql

BEGIN;

-- Processing 75 hero images

-- Update hero image: Q3 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Audi-q3-2025.jpg' WHERE id = '42fbd3d1-fe4d-4e2d-a8b7-fd15eea38619';

-- Update hero image: Q3 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Audi-q3-2025.jpg' WHERE id = '4c8d7e74-e8ef-43af-ad8b-645da6c1a11e';

-- Update hero image: Q7 2024
UPDATE models SET hero_image_url = '/images/vehicles/hero/Audi-q7-2024-25.jpg' WHERE id = 'c5d34118-09f9-4140-9874-8732ce1760f4';

-- Update hero image: Q7 2024
UPDATE models SET hero_image_url = '/images/vehicles/hero/Audi-q7-2025.jpg' WHERE id = 'c5d34118-09f9-4140-9874-8732ce1760f4';

-- Update hero image: Q7 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Audi-q7-2025.jpg' WHERE id = '33cd0132-59a7-4f91-8f67-87454bb36f92';

-- Update hero image: X5 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/BMW-x5-lci-2024.jpg' WHERE id = '783e5298-6fde-4a60-9504-b10430f99b1f';

-- Update hero image: X5 2024
UPDATE models SET hero_image_url = '/images/vehicles/hero/BMW-x5-lci-2024.jpg' WHERE id = '1cfe08a0-5701-4f74-841a-50f62f9317c6';

-- Update hero image: X5 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/BMW-x5-lci-2025.jpg' WHERE id = '783e5298-6fde-4a60-9504-b10430f99b1f';

-- Update hero image: X5 2024
UPDATE models SET hero_image_url = '/images/vehicles/hero/BMW-x5-lci-2025.jpg' WHERE id = '1cfe08a0-5701-4f74-841a-50f62f9317c6';

-- Update hero image: Arrizo 5
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-arrizo-5-2024.jpg' WHERE id = 'bbd3c43e-5c7d-473a-9634-3b35ba1fe10a';

-- Update hero image: Arrizo 5 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-arrizo-5-2024.jpg' WHERE id = 'df70e15a-8c36-4cf8-a68e-fcdb7b9e0bab';

-- Update hero image: Arrizo 5 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-arrizo-5-2024.jpg' WHERE id = 'edd500db-4ec5-4aa8-b6f9-bf9d7025a42e';

-- Update hero image: Arrizo 8 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-arrizo-8-2025.jpg' WHERE id = '7344ae20-afce-4842-baec-e184cbd1fbe5';

-- Update hero image: Tiggo 3 2024
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-tiggo-3-2024.jpg' WHERE id = 'd55ceb2d-b46b-4e1a-8fa0-976854231fca';

-- Update hero image: Tiggo 4 Pro 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-tiggo-4-pro-2025.jpg' WHERE id = '0ff2e1b4-ccdd-4169-ba12-4c4062c61e06';

-- Update hero image: Tiggo 4 Pro 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-tiggo-4-pro-2025.jpg' WHERE id = 'f4bbe1c9-4688-49d1-8b82-d43e3691c85c';

-- Update hero image: Tiggo 7
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-tiggo-7-pro-max-2025.jpg' WHERE id = '6dcfc2c6-aec6-42fb-a0cf-e807deefb80e';

-- Update hero image: Tiggo 7 Pro Max 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-tiggo-7-pro-max-2025.jpg' WHERE id = '0588661b-bae4-4446-8fce-81bfd4b2a12a';

-- Update hero image: Tiggo 8 Pro 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-tiggo-8-pro-2024.jpg' WHERE id = '9bc20719-3898-48ad-abdb-cfd8625e0bbc';

-- Update hero image: Tiggo 8 Pro Max 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-tiggo-8-pro-2024.jpg' WHERE id = 'edeade5b-14ac-428b-aeec-9202ac9b5350';

-- Update hero image: Tiggo 8 Pro 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-tiggo-8-pro-2024.jpg' WHERE id = 'ff7daffe-e140-4c36-ad79-56fe49f752b6';

-- Update hero image: Tiggo 8 Pro Max 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chery-tiggo-8-pro-max-2025.jpg' WHERE id = 'edeade5b-14ac-428b-aeec-9202ac9b5350';

-- Update hero image: Captiva 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chevrolet-captiva-2025.jpg' WHERE id = 'f566f661-e41e-43a3-b69f-a4ad6d4cd81c';

-- Update hero image: Optra 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chevrolet-optra-2026.jpg' WHERE id = 'a6982efc-ae03-4043-8062-d242c7bc13dc';

-- Update hero image: Optra 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Chevrolet-optra-2026.jpg' WHERE id = 'd32fa82f-dc93-427b-bbd5-c92aa807ce1c';

-- Update hero image: Elantra CN7
UPDATE models SET hero_image_url = '/images/vehicles/hero/Hyundai-elantra-cn7-2024.jpg' WHERE id = 'a90073f3-7799-47e3-9b4c-62df482d0650';

-- Update hero image: Elantra CN7
UPDATE models SET hero_image_url = '/images/vehicles/hero/Hyundai-elantra-cn7-smart-prime-2025.jpg' WHERE id = 'a90073f3-7799-47e3-9b4c-62df482d0650';

-- Update hero image: Tucson NX4
UPDATE models SET hero_image_url = '/images/vehicles/hero/Hyundai-tucson-nx4-2024.jpg' WHERE id = '5ce9231f-1519-48a0-9aa8-9c287b90bba1';

-- Update hero image: Tucson NX4 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Hyundai-tucson-nx4-2024.jpg' WHERE id = 'd9a1b0d9-0059-49c6-b0a3-9e33bc30c036';

-- Update hero image: Tucson NX4
UPDATE models SET hero_image_url = '/images/vehicles/hero/Hyundai-tucson-nx4-premium-2025.jpg' WHERE id = '5ce9231f-1519-48a0-9aa8-9c287b90bba1';

-- Update hero image: Grand Cerato
UPDATE models SET hero_image_url = '/images/vehicles/hero/Kia-grand-cerato-2024.jpg' WHERE id = 'ce9a7478-4bea-4f21-aac7-0f02efc90f16';

-- Update hero image: Sportage
UPDATE models SET hero_image_url = '/images/vehicles/hero/Kia-sportage-2025.jpg' WHERE id = '920363ae-ee73-4e52-9c21-5e465002b265';

-- Update hero image: Sportage 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Kia-sportage-2025.jpg' WHERE id = '5da707f0-2ef7-459d-996b-833d0cfadb20';

-- Update hero image: MG HS Luxury 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-hs-2024.jpg' WHERE id = '3240f36b-0251-4a90-98cc-2aa5a4c75166';

-- Update hero image: MG HS Luxury 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-hs-2024.jpg' WHERE id = 'ebd32046-0a38-432d-8f58-4e6eeb3d1bc7';

-- Update hero image: MG HS 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-hs-2024.jpg' WHERE id = '70cb3ae4-49e4-480f-8a35-c94a49c808b8';

-- Update hero image: MG 5
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-5-2025.jpg' WHERE id = 'e0ea6b2c-e328-4cca-8fc2-690310da4682';

-- Update hero image: MG 5 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-5-2025.jpg' WHERE id = '6d8c2fd6-2000-4de0-a5de-1974e8d7daf8';

-- Update hero image: MG 5 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-5-2025.jpg' WHERE id = 'ae5f901d-9dcf-41de-9789-6eef7c13732c';

-- Update hero image: MG 5
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-5-amended-2025.jpg' WHERE id = 'e0ea6b2c-e328-4cca-8fc2-690310da4682';

-- Update hero image: MG 6 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-6-2024.jpg' WHERE id = 'a13f0e68-c844-409d-a430-35707a68594c';

-- Update hero image: MG 6 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-6-2024.jpg' WHERE id = '25fb3985-7a0f-43c5-bf26-d85ff74c54ec';

-- Update hero image: MG HS Luxury 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-hs-2025.jpg' WHERE id = '3240f36b-0251-4a90-98cc-2aa5a4c75166';

-- Update hero image: MG HS Luxury 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-hs-2025.jpg' WHERE id = 'ebd32046-0a38-432d-8f58-4e6eeb3d1bc7';

-- Update hero image: MG HS 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-hs-2025.jpg' WHERE id = '70cb3ae4-49e4-480f-8a35-c94a49c808b8';

-- Update hero image: ZS
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-zs-lux-2025.jpg' WHERE id = '755ac35b-ef04-4e48-a4f0-cc43021bd029';

-- Update hero image: MG ZS Luxury 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-mg-zs-lux-2025.jpg' WHERE id = '003276dd-826d-4a0f-a908-f48f9e0c7134';

-- Update hero image: MG RX5 Plus 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-rx5-2025.jpg' WHERE id = '65b0ea95-c7f5-4768-bd8a-1c011f4556e7';

-- Update hero image: MG RX5 Plus 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-rx5-2025.jpg' WHERE id = '442d506b-34b4-47bd-a85a-8aef5d61f8b0';

-- Update hero image: ZS
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-zs-2024.jpg' WHERE id = '755ac35b-ef04-4e48-a4f0-cc43021bd029';

-- Update hero image: MG ZS Luxury 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-zs-2024.jpg' WHERE id = '003276dd-826d-4a0f-a908-f48f9e0c7134';

-- Update hero image: MG ZS 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-zs-2024.jpg' WHERE id = 'fc7f9ff6-7f72-4f92-9ea0-6078015ce503';

-- Update hero image: MG ZS 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/MG-zs-2024.jpg' WHERE id = '097db926-6a2a-4b38-8bba-549bbaf5b9bc';

-- Update hero image: Sentra 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Nissan-sentra-2025.jpg' WHERE id = '3e133fc9-a252-4829-8251-16044317957a';

-- Update hero image: Sunny
UPDATE models SET hero_image_url = '/images/vehicles/hero/Nissan-sunny-2025.jpg' WHERE id = '1f8cabc1-a131-491c-837b-52b0d3ef9311';

-- Update hero image: Sunny 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Nissan-sunny-2025.jpg' WHERE id = 'a3d3bbea-3fcd-4cc7-bf26-7dcbbec0ffa0';

-- Update hero image: Duster
UPDATE models SET hero_image_url = '/images/vehicles/hero/Renault-duster-2024.jpg' WHERE id = '09c409d3-2ab9-4135-86d0-63725a0d4d01';

-- Update hero image: Duster 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Renault-duster-2024.jpg' WHERE id = '785d2000-d486-443a-bc99-7d02daa3fe1c';

-- Update hero image: Duster 2025 New Generation
UPDATE models SET hero_image_url = '/images/vehicles/hero/Renault-duster-2024.jpg' WHERE id = '48764a96-7797-4af5-891b-e46a7648368b';

-- Update hero image: Megane
UPDATE models SET hero_image_url = '/images/vehicles/hero/Renault-megane-2024.jpg' WHERE id = '163e27fa-8f96-4f11-b5d4-573ca52b5105';

-- Update hero image: Megane 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Renault-megane-2024.jpg' WHERE id = 'aec9bf5d-8671-42fb-b6a8-6a11d41c6af7';

-- Update hero image: Megane 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Renault-megane-2024.jpg' WHERE id = 'e44b6aff-4b94-4315-98fa-d9ea54323178';

-- Update hero image: Megane
UPDATE models SET hero_image_url = '/images/vehicles/hero/Renault-megane-grand-coupé-2025.jpg' WHERE id = '163e27fa-8f96-4f11-b5d4-573ca52b5105';

-- Update hero image: Camry 2024
UPDATE models SET hero_image_url = '/images/vehicles/hero/Toyota-camry-2024.jpg' WHERE id = 'c1b1261d-cb2a-4771-bc64-09bcf516fccd';

-- Update hero image: Camry 2024
UPDATE models SET hero_image_url = '/images/vehicles/hero/Toyota-camry-2025.jpg' WHERE id = 'c1b1261d-cb2a-4771-bc64-09bcf516fccd';

-- Update hero image: Corolla
UPDATE models SET hero_image_url = '/images/vehicles/hero/Toyota-corolla-2026.jpg' WHERE id = 'b926310d-5e07-4abb-b0aa-b649f8b25447';

-- Update hero image: Corolla 2026
UPDATE models SET hero_image_url = '/images/vehicles/hero/Toyota-corolla-2026.jpg' WHERE id = '7e7b0964-52b1-4e46-a7db-def2f48b9c20';

-- Update hero image: Corolla 2025
UPDATE models SET hero_image_url = '/images/vehicles/hero/Toyota-corolla-2026.jpg' WHERE id = '53952e0f-8683-41af-962e-85f0870fc699';

-- Update hero image: Corolla
UPDATE models SET hero_image_url = '/images/vehicles/hero/Toyota-corolla-all-trims-2026.jpg' WHERE id = 'b926310d-5e07-4abb-b0aa-b649f8b25447';

-- Update hero image: RAV4 2024
UPDATE models SET hero_image_url = '/images/vehicles/hero/Toyota-rav4-2024.jpg' WHERE id = 'e32b8370-728d-47a4-abd8-712aa1fe7988';

-- Update hero image: RAV4 2024
UPDATE models SET hero_image_url = '/images/vehicles/hero/Toyota-rav4-2025.jpg' WHERE id = 'e32b8370-728d-47a4-abd8-712aa1fe7988';

-- Processing 60 hover images

-- Update hover image: Q7 2024
UPDATE models SET hover_image_url = '/images/vehicles/hover/Audi-q7-2024-25.jpg' WHERE id = 'c5d34118-09f9-4140-9874-8732ce1760f4';

-- Update hover image: Q7 2024
UPDATE models SET hover_image_url = '/images/vehicles/hover/Audi-q7-2025.jpg' WHERE id = 'c5d34118-09f9-4140-9874-8732ce1760f4';

-- Update hover image: Q7 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/Audi-q7-2025.jpg' WHERE id = '33cd0132-59a7-4f91-8f67-87454bb36f92';

-- Update hover image: Arrizo 5
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chery-arrizo-5-2024.jpg' WHERE id = 'bbd3c43e-5c7d-473a-9634-3b35ba1fe10a';

-- Update hover image: Arrizo 5 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chery-arrizo-5-2024.jpg' WHERE id = 'df70e15a-8c36-4cf8-a68e-fcdb7b9e0bab';

-- Update hover image: Arrizo 5 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chery-arrizo-5-2024.jpg' WHERE id = 'edd500db-4ec5-4aa8-b6f9-bf9d7025a42e';

-- Update hover image: Arrizo 8 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chery-arrizo-8-2025.jpg' WHERE id = '7344ae20-afce-4842-baec-e184cbd1fbe5';

-- Update hover image: Tiggo 7
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chery-tiggo-7-pro-max-2025.jpg' WHERE id = '6dcfc2c6-aec6-42fb-a0cf-e807deefb80e';

-- Update hover image: Tiggo 7 Pro Max 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chery-tiggo-7-pro-max-2025.jpg' WHERE id = '0588661b-bae4-4446-8fce-81bfd4b2a12a';

-- Update hover image: Tiggo 8 Pro 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chery-tiggo-8-pro-2024.jpg' WHERE id = '9bc20719-3898-48ad-abdb-cfd8625e0bbc';

-- Update hover image: Tiggo 8 Pro Max 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chery-tiggo-8-pro-2024.jpg' WHERE id = 'edeade5b-14ac-428b-aeec-9202ac9b5350';

-- Update hover image: Tiggo 8 Pro 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chery-tiggo-8-pro-2024.jpg' WHERE id = 'ff7daffe-e140-4c36-ad79-56fe49f752b6';

-- Update hover image: Tiggo 8 Pro Max 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chery-tiggo-8-pro-max-2025.jpg' WHERE id = 'edeade5b-14ac-428b-aeec-9202ac9b5350';

-- Update hover image: Captiva 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chevrolet-captiva-2025.jpg' WHERE id = 'f566f661-e41e-43a3-b69f-a4ad6d4cd81c';

-- Update hover image: Optra 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chevrolet-optra-2026.jpg' WHERE id = 'a6982efc-ae03-4043-8062-d242c7bc13dc';

-- Update hover image: Optra 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/Chevrolet-optra-2026.jpg' WHERE id = 'd32fa82f-dc93-427b-bbd5-c92aa807ce1c';

-- Update hover image: Elantra CN7
UPDATE models SET hover_image_url = '/images/vehicles/hover/Hyundai-elantra-cn7-2024.jpg' WHERE id = 'a90073f3-7799-47e3-9b4c-62df482d0650';

-- Update hover image: Elantra CN7
UPDATE models SET hover_image_url = '/images/vehicles/hover/Hyundai-elantra-cn7-smart-prime-2025.jpg' WHERE id = 'a90073f3-7799-47e3-9b4c-62df482d0650';

-- Update hover image: Tucson NX4
UPDATE models SET hover_image_url = '/images/vehicles/hover/Hyundai-tucson-nx4-2024.jpg' WHERE id = '5ce9231f-1519-48a0-9aa8-9c287b90bba1';

-- Update hover image: Tucson NX4 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/Hyundai-tucson-nx4-2024.jpg' WHERE id = 'd9a1b0d9-0059-49c6-b0a3-9e33bc30c036';

-- Update hover image: Tucson NX4
UPDATE models SET hover_image_url = '/images/vehicles/hover/Hyundai-tucson-nx4-premium-2025.jpg' WHERE id = '5ce9231f-1519-48a0-9aa8-9c287b90bba1';

-- Update hover image: Grand Cerato
UPDATE models SET hover_image_url = '/images/vehicles/hover/Kia-grand-cerato-2024.jpg' WHERE id = 'ce9a7478-4bea-4f21-aac7-0f02efc90f16';

-- Update hover image: Sportage
UPDATE models SET hover_image_url = '/images/vehicles/hover/Kia-sportage-2025.jpg' WHERE id = '920363ae-ee73-4e52-9c21-5e465002b265';

-- Update hover image: Sportage 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/Kia-sportage-2025.jpg' WHERE id = '5da707f0-2ef7-459d-996b-833d0cfadb20';

-- Update hover image: MG HS Luxury 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-hs-2024.jpg' WHERE id = '3240f36b-0251-4a90-98cc-2aa5a4c75166';

-- Update hover image: MG HS Luxury 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-hs-2024.jpg' WHERE id = 'ebd32046-0a38-432d-8f58-4e6eeb3d1bc7';

-- Update hover image: MG HS 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-hs-2024.jpg' WHERE id = '70cb3ae4-49e4-480f-8a35-c94a49c808b8';

-- Update hover image: MG 5
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-5-2025.jpg' WHERE id = 'e0ea6b2c-e328-4cca-8fc2-690310da4682';

-- Update hover image: MG 5 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-5-2025.jpg' WHERE id = '6d8c2fd6-2000-4de0-a5de-1974e8d7daf8';

-- Update hover image: MG 5 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-5-2025.jpg' WHERE id = 'ae5f901d-9dcf-41de-9789-6eef7c13732c';

-- Update hover image: MG 5
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-5-amended-2025.jpg' WHERE id = 'e0ea6b2c-e328-4cca-8fc2-690310da4682';

-- Update hover image: MG 6 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-6-2024.jpg' WHERE id = 'a13f0e68-c844-409d-a430-35707a68594c';

-- Update hover image: MG 6 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-6-2024.jpg' WHERE id = '25fb3985-7a0f-43c5-bf26-d85ff74c54ec';

-- Update hover image: MG HS Luxury 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-hs-2025.jpg' WHERE id = '3240f36b-0251-4a90-98cc-2aa5a4c75166';

-- Update hover image: MG HS Luxury 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-hs-2025.jpg' WHERE id = 'ebd32046-0a38-432d-8f58-4e6eeb3d1bc7';

-- Update hover image: MG HS 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-hs-2025.jpg' WHERE id = '70cb3ae4-49e4-480f-8a35-c94a49c808b8';

-- Update hover image: ZS
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-zs-lux-2025.jpg' WHERE id = '755ac35b-ef04-4e48-a4f0-cc43021bd029';

-- Update hover image: MG ZS Luxury 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-mg-zs-lux-2025.jpg' WHERE id = '003276dd-826d-4a0f-a908-f48f9e0c7134';

-- Update hover image: MG RX5 Plus 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-rx5-2025.jpg' WHERE id = '65b0ea95-c7f5-4768-bd8a-1c011f4556e7';

-- Update hover image: MG RX5 Plus 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-rx5-2025.jpg' WHERE id = '442d506b-34b4-47bd-a85a-8aef5d61f8b0';

-- Update hover image: ZS
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-zs-2024.jpg' WHERE id = '755ac35b-ef04-4e48-a4f0-cc43021bd029';

-- Update hover image: MG ZS Luxury 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-zs-2024.jpg' WHERE id = '003276dd-826d-4a0f-a908-f48f9e0c7134';

-- Update hover image: MG ZS 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-zs-2024.jpg' WHERE id = 'fc7f9ff6-7f72-4f92-9ea0-6078015ce503';

-- Update hover image: MG ZS 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/MG-zs-2024.jpg' WHERE id = '097db926-6a2a-4b38-8bba-549bbaf5b9bc';

-- Update hover image: Sentra 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/Nissan-sentra-2025.jpg' WHERE id = '3e133fc9-a252-4829-8251-16044317957a';

-- Update hover image: Sunny
UPDATE models SET hover_image_url = '/images/vehicles/hover/Nissan-sunny-2025.jpg' WHERE id = '1f8cabc1-a131-491c-837b-52b0d3ef9311';

-- Update hover image: Sunny 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/Nissan-sunny-2025.jpg' WHERE id = 'a3d3bbea-3fcd-4cc7-bf26-7dcbbec0ffa0';

-- Update hover image: Duster
UPDATE models SET hover_image_url = '/images/vehicles/hover/Renault-duster-2024.jpg' WHERE id = '09c409d3-2ab9-4135-86d0-63725a0d4d01';

-- Update hover image: Duster 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/Renault-duster-2024.jpg' WHERE id = '785d2000-d486-443a-bc99-7d02daa3fe1c';

-- Update hover image: Duster 2025 New Generation
UPDATE models SET hover_image_url = '/images/vehicles/hover/Renault-duster-2024.jpg' WHERE id = '48764a96-7797-4af5-891b-e46a7648368b';

-- Update hover image: Camry 2024
UPDATE models SET hover_image_url = '/images/vehicles/hover/Toyota-camry-2024.jpg' WHERE id = 'c1b1261d-cb2a-4771-bc64-09bcf516fccd';

-- Update hover image: Camry 2024
UPDATE models SET hover_image_url = '/images/vehicles/hover/Toyota-camry-2025.jpg' WHERE id = 'c1b1261d-cb2a-4771-bc64-09bcf516fccd';

-- Update hover image: Corolla
UPDATE models SET hover_image_url = '/images/vehicles/hover/Toyota-corolla-2026.jpg' WHERE id = 'b926310d-5e07-4abb-b0aa-b649f8b25447';

-- Update hover image: Corolla 2026
UPDATE models SET hover_image_url = '/images/vehicles/hover/Toyota-corolla-2026.jpg' WHERE id = '7e7b0964-52b1-4e46-a7db-def2f48b9c20';

-- Update hover image: Corolla 2025
UPDATE models SET hover_image_url = '/images/vehicles/hover/Toyota-corolla-2026.jpg' WHERE id = '53952e0f-8683-41af-962e-85f0870fc699';

-- Update hover image: Corolla
UPDATE models SET hover_image_url = '/images/vehicles/hover/Toyota-corolla-all-trims-2026.jpg' WHERE id = 'b926310d-5e07-4abb-b0aa-b649f8b25447';

-- Update hover image: RAV4 2024
UPDATE models SET hover_image_url = '/images/vehicles/hover/Toyota-rav4-2024.jpg' WHERE id = 'e32b8370-728d-47a4-abd8-712aa1fe7988';

-- Update hover image: RAV4 2024
UPDATE models SET hover_image_url = '/images/vehicles/hover/Toyota-rav4-2025.jpg' WHERE id = 'e32b8370-728d-47a4-abd8-712aa1fe7988';

COMMIT;

-- Statistics:
--   Hero images matched: 71
--   Hero images unmatched: 36
--   Hover images matched: 58
--   Hover images unmatched: 28
--   Total UPDATE statements: 129
